name: Telegram Daily 7am KST (KRX Volume Spike)

on:
  schedule:
    # 일~목 22:00(UTC) = 월~금 07:00(KST)
    - cron: "0 22 * * 0-4"   # 또는 "0 22 * * SUN-THU"
  workflow_dispatch: {}

jobs:
  send:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pykrx pandas

      - name: Run report & send to Telegram
        run: python daily_krx_volume_spike.py
        
