name: Telegram Daily 7am KST (KRX Volume Spike)

on:
  schedule:
    # KST 07:00 == 전일 UTC 22:00
    - cron: "0 22 * * *"
  workflow_dispatch: {}

jobs:
  send:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pykrx pandas

      - name: Run report & send to Telegram
        run: python daily_krx_volume_spike.py
        
